# Generated by Django 5.1.1 on 2024-10-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_email_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='attachement',
            field=models.FileField(blank=True, upload_to='email_attachement/'),
        ),
    ]
